name: release_ecr

on:
  push:
    branches:
      - feature/move_to_ecr
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Public ECR
        uses: docker/login-action@v1
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        env:
          AWS_REGION: us-east-1

      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: echo 111
      #   run: docker build . -f Dockerfile -t maticinsurance/gocd-agent:latest
      # - name: Define Docker tag
      #   run: echo "${GITHUB_REF/refs\/tags\//}" > docker.tag
      # - name: Tag docker image
      #   run: docker tag maticinsurance/gocd-agent:latest maticinsurance/gocd-agent:$(<docker.tag)
      # - name: Login to Docker
      #   run: docker login -u ${{ secrets.AWS_ACCESS_KEY_ID }} -p ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      # - name: Push latest image
      #   run: docker push maticinsurance/gocd-agent:latest
      # - name: Push tagged image
      #   run: docker push maticinsurance/gocd-agent:$(<docker.tag)