name: release_ecr

on:
  push:
    branches:
      - feature/move_to_ecr
 
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ECR_REGISTRY: public.ecr.aws
      ECR_REPOSITORY: matic
    steps:
      - name: Login to Public ECR
        uses: docker/login-action@v1
        with:
          registry: ${{env.ECR_REGISTRY}}
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # logout: true
        env:
          AWS_REGION: us-east-1
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: docker build . -f Dockerfile -t ${{env.ECR_REGISTRY}}/${{env.ECR_REPOSITORY}}/gocd-agent:latest
      - name: Define Docker tag
        # run: echo "${GITHUB_REF/refs\/tags\//}" > docker.tag
        run: echo "v0.1.2" > docker.tag
      - name: Tag docker image
        run: docker tag ${{env.ECR_REGISTRY}}/${{env.ECR_REPOSITORY}}/gocd-agent:latest ${{env.ECR_REGISTRY}}/${{env.ECR_REPOSITORY}}/gocd-agent:$(<docker.tag)
      - name: Push latest image
        run: docker push ${{env.ECR_REGISTRY}}/${{env.ECR_REPOSITORY}}/gocd-agent:latest
      - name: Push tagged image
        run: docker push ${{env.ECR_REGISTRY}}/${{env.ECR_REPOSITORY}}/gocd-agent:$(<docker.tag)