name: release_ecr

on:
  push:
    branches:
      - feature/move_to_ecr
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Define Docker tag
        run: echo "${GITHUB_REF/refs\/tags\//}" > docker.tag

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: matic
        run: |
          echo $ECR_REGISTRY/$ECR_REPOSITORY
          # docker build . -f Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY/gocd-agent:v0.0.1
          # docker push $ECR_REGISTRY/$ECR_REPOSITORY/gocd-agent:v0.0.1
          # echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY/gocd-agent:v0.0.1"

      - name: Log out of Amazon ECR
        if: always()
        run: docker logout ${{ steps.login-ecr.outputs.registry }}

